# Generated by Django 4.2.23 on 2025-07-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_enhance_multimedia_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawnews',
            name='type',
            field=models.CharField(choices=[('audio', '音频'), ('video', '视频'), ('article', '文章')], default='article', max_length=20, verbose_name='内容类型'),
        ),
    ]
