# Generated by Django 5.2.4 on 2025-07-20 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rawnews_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioArticleSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_map', models.JSONField(help_text='如[{"audio_time": 12, "article_pos": 3}]', verbose_name='同步点映射')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_maps', to='content.article')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_maps', to='content.audiocontent')),
            ],
        ),
        migrations.CreateModel(
            name='UserPlayProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('audio', '音频'), ('video', '视频'), ('article', '文章')], max_length=20, verbose_name='内容类型')),
                ('content_id', models.BigIntegerField(verbose_name='内容ID')),
                ('progress', models.IntegerField(default=0, help_text='单位：秒或百分比', verbose_name='进度')),
                ('last_played_at', models.DateTimeField(auto_now=True, verbose_name='最后播放时间')),
                ('extra_data', models.JSONField(blank=True, null=True, verbose_name='扩展信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='play_progresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'content_id')},
            },
        ),
    ]
