# Generated by Django 5.2.4 on 2025-07-20 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_audioarticlesync_userplayprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videocontent',
            options={'verbose_name': '视频内容', 'verbose_name_plural': '视频内容'},
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_status_782842_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_publish_8c4764_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_is_feat_1e5ff0_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_is_tren_e8a4ca_idx',
        ),
        migrations.RenameField(
            model_name='videocontent',
            old_name='chapters',
            new_name='chapter_info',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='aspect_ratio',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='audio_tracks',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='author',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='auto_play',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='category',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='description',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_trending',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='loop',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='published_at',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='quality_level',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='search_keywords',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='source',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='status',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='subtitles',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='timestamps',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_qualities',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='backup_video_urls',
            field=models.JSONField(blank=True, null=True, verbose_name='备用视频URL数组'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='cdn_distribution',
            field=models.JSONField(blank=True, null=True, verbose_name='CDN分发信息'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='下载次数'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='frame_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='帧率'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='是否为直播'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='live_stream_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='直播流地址'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='news',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='video_content', to='content.rawnews', verbose_name='关联资讯元数据'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontent',
            name='play_count',
            field=models.BigIntegerField(default=0, verbose_name='播放次数'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='海报图'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='subtitle_urls',
            field=models.JSONField(blank=True, null=True, verbose_name='字幕文件URL数组'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='transcription',
            field=models.TextField(blank=True, null=True, verbose_name='视频转录文字'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='upload_status',
            field=models.CharField(choices=[('uploading', '上传中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='上传状态'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_description',
            field=models.TextField(blank=True, null=True, verbose_name='视频描述'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_quality',
            field=models.CharField(choices=[('sd', '标清'), ('hd', '高清'), ('4k', '4K')], default='hd', max_length=10, verbose_name='视频质量'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_tags',
            field=models.JSONField(blank=True, null=True, verbose_name='视频标签'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='codec',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='编码格式'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='视频时长(秒)'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(max_length=500, verbose_name='视频文件URL'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['duration'], name='content_vid_duratio_6ceca9_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['resolution'], name='content_vid_resolut_2366e7_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['video_quality'], name='content_vid_video_q_957c23_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['is_live'], name='content_vid_is_live_fbd67c_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['play_count'], name='content_vid_play_co_627df2_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['upload_status'], name='content_vid_upload__d41539_idx'),
        ),
        migrations.AddConstraint(
            model_name='videocontent',
            constraint=models.UniqueConstraint(fields=('news',), name='unique_news_video'),
        ),
    ]
