# Generated by Django 5.2.4 on 2025-07-20 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_videocontent_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audioarticlesync',
            name='article',
        ),
        migrations.RemoveField(
            model_name='audioarticlesync',
            name='audio',
        ),
        migrations.AlterUniqueTogether(
            name='userplayprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userplayprogress',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='videocontent',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': '视频', 'verbose_name_plural': '视频'},
        ),
        migrations.RemoveConstraint(
            model_name='videocontent',
            name='unique_news_video',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_duratio_6ceca9_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_resolut_2366e7_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_video_q_957c23_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_is_live_fbd67c_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_play_co_627df2_idx',
        ),
        migrations.RemoveIndex(
            model_name='videocontent',
            name='content_vid_upload__d41539_idx',
        ),
        migrations.RenameField(
            model_name='videocontent',
            old_name='chapter_info',
            new_name='chapters',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='backup_video_urls',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='cdn_distribution',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='download_count',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='frame_rate',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='live_stream_url',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='news',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='play_count',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='subtitle_urls',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='transcription',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='upload_status',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_description',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_quality',
        ),
        migrations.RemoveField(
            model_name='videocontent',
            name='video_tags',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='aspect_ratio',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='宽高比'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='audio_tracks',
            field=models.JSONField(blank=True, null=True, verbose_name='音轨信息'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='作者'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='auto_play',
            field=models.BooleanField(default=False, verbose_name='自动播放'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='content.contentcategory', verbose_name='分类'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='封面图片'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_videos', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='extra_data',
            field=models.JSONField(blank=True, null=True, verbose_name='扩展数据'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='是否付费内容'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='keywords',
            field=models.JSONField(blank=True, null=True, verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='loop',
            field=models.BooleanField(default=False, verbose_name='循环播放'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='meta_description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SEO描述'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='quality_level',
            field=models.CharField(choices=[('low', '一般'), ('medium', '良好'), ('high', '优质'), ('premium', '精品')], default='medium', max_length=20, verbose_name='质量等级'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='定时发布时间'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='search_keywords',
            field=models.TextField(blank=True, null=True, verbose_name='搜索关键词'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, verbose_name='URL标识'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='source',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='来源'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='原始链接'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('published', '已发布'), ('archived', '已归档'), ('deleted', '已删除')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='副标题'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='subtitles',
            field=models.JSONField(blank=True, null=True, verbose_name='字幕信息'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='summary',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='tags',
            field=models.ManyToManyField(blank=True, to='content.contenttag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='timestamps',
            field=models.JSONField(blank=True, null=True, verbose_name='时间戳标记'),
        ),
        migrations.AddField(
            model_name='videocontent',
            name='title',
            field=models.CharField(default=1, max_length=500, verbose_name='标题'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocontent',
            name='video_qualities',
            field=models.JSONField(blank=True, null=True, verbose_name='多清晰度链接'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='codec',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='编码格式'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='时长(秒)'),
        ),
        migrations.AlterField(
            model_name='videocontent',
            name='video_url',
            field=models.URLField(max_length=500, verbose_name='视频链接'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['status'], name='content_vid_status_782842_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['published_at'], name='content_vid_publish_8c4764_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['is_featured'], name='content_vid_is_feat_1e5ff0_idx'),
        ),
        migrations.AddIndex(
            model_name='videocontent',
            index=models.Index(fields=['is_trending'], name='content_vid_is_tren_e8a4ca_idx'),
        ),
        migrations.DeleteModel(
            name='AudioArticleSync',
        ),
        migrations.DeleteModel(
            name='UserPlayProgress',
        ),
    ]
