# Generated by Django 5.2.4 on 2025-07-20 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='最后登录IP'),
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='zh-CN', max_length=10, verbose_name='语言')),
                ('theme', models.CharField(default='light', max_length=20, verbose_name='主题')),
                ('notification_settings', models.JSONField(blank=True, default=dict, null=True, verbose_name='通知设置')),
                ('playback_speed', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='播放速度')),
                ('content_filter', models.JSONField(blank=True, default=dict, null=True, verbose_name='内容过滤')),
                ('privacy_settings', models.JSONField(blank=True, default=dict, null=True, verbose_name='隐私设置')),
                ('tts_voice', models.CharField(blank=True, max_length=50, null=True, verbose_name='TTS语音')),
                ('tts_speed', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='TTS语速')),
                ('tts_pitch', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='TTS音调')),
                ('tts_volume', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='TTS音量')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放')),
                ('auto_download', models.BooleanField(default=False, verbose_name='自动下载')),
                ('show_explicit_content', models.BooleanField(default=False, verbose_name='显示敏感内容')),
                ('show_recommendations', models.BooleanField(default=True, verbose_name='显示推荐')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='出生日期')),
                ('age_group', models.CharField(default='unknown', max_length=20, verbose_name='年龄段')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='位置')),
                ('interest_categories', models.JSONField(blank=True, null=True, verbose_name='兴趣分类')),
                ('preferred_content_length', models.CharField(default='mixed', max_length=20, verbose_name='偏好内容长度')),
                ('preferred_time_slots', models.JSONField(blank=True, null=True, verbose_name='偏好时间段')),
                ('active_days', models.JSONField(blank=True, null=True, verbose_name='活跃天')),
                ('device_preference', models.CharField(default='mobile', max_length=20, verbose_name='设备偏好')),
                ('content_freshness_preference', models.DecimalField(decimal_places=2, default=0.7, max_digits=3, verbose_name='内容新鲜度偏好')),
                ('diversity_preference', models.DecimalField(decimal_places=2, default=0.5, max_digits=3, verbose_name='多样性偏好')),
                ('interaction_frequency', models.CharField(default='medium', max_length=20, verbose_name='互动频率')),
                ('social_activity_level', models.CharField(default='lurker', max_length=20, verbose_name='社交活跃度')),
                ('news_reading_speed', models.CharField(default='normal', max_length=20, verbose_name='新闻阅读速度')),
                ('sentiment_preference', models.CharField(default='mixed', max_length=20, verbose_name='情感偏好')),
                ('last_updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
